name = "Backtest"
uuid = "97e15993-006f-405e-8a50-6742026716c5"
version = "1.0.0-DEV"
authors = ["Adam Wilson <adamwilson99@hotmail.com> and contributors"]

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
YFinance = "e4b3b0a2-f9a3-42f3-aabb-32142cceaf77"

[compat]
Chain = "1.0.0"
DataFrames = "1.8.1"
DataFramesMeta = "0.15.6"
YFinance = "0.1.11"
julia = "1.10"

[extras]
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReTestItems", "Test"]
