name = "Backtest"
uuid = "97e15993-006f-405e-8a50-6742026716c5"
version = "1.0.0-DEV"
authors = ["Adam Wilson <adamwilson99@hotmail.com> and contributors"]

[deps]
YFinance = "e4b3b0a2-f9a3-42f3-aabb-32142cceaf77"

[compat]
YFinance = "0.1.11"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
