name = "Backtest"
uuid = "97e15993-006f-405e-8a50-6742026716c5"
version = "1.0.0-DEV"
authors = ["Adam Wilson <adamwilson99@hotmail.com> and contributors"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
YFinance = "e4b3b0a2-f9a3-42f3-aabb-32142cceaf77"

[compat]
BenchmarkTools = "1.6.3"
Chain = "1.0.0"
Combinatorics = "1.1.0"
DataFrames = "1.8.1"
DataFramesMeta = "0.15.6"
Dates = "1.11.0"
Logging = "1.11.0"
LoopVectorization = "0.12.173"
Polyester = "0.7.18"
ShiftedArrays = "2.0.0"
YFinance = "0.1.11"
julia = "1.10.10"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"

[targets]
test = ["JET", "ReTestItems", "Statistics", "Test"]
